# Master list of canonical product names (cleaned, no symbols)
CANONICAL_PRODUCTS = [
    "Patriot dark grey", "Patriot Tabaco", "Liberty DK grey", "Liberty Black", "Style black",
    "Titan black", "Icon black", "Onix black", "Dynamic black", "Orbital black",
    "Sky black", "Coin grey", "Coin black", "Coin blue", "Patriot black",
    "Fc col 31", "Fc col 30", "R 5 c", "FC col 23 Gris", "FCB BMW 2",
    "Fc col 23", "Fc col 14 perforada", "Bmw", "FC col 29", "Fc crepe noir",
    "Fc enigma", "Techo gris claro", "Techo beige", "Techo black",
    "Diseno 1 black", "Diseno 1 blue", "Diseno 1 dark grey", "Diseno 1 red",
    "Diseno 6 black", "Diseno 3 black", "Diseno perforado red", "Diseno perforado black",
    "Diseno perforado azul", "Diseno perforado DK grey",
    "C 97 Black", "C 97 azul", "C 97 rojo", "C 97 plata",
    "C 20 rojo", "C 20 plata", "C 20 azul",
    "Cuero 7 R C", "Cuero 4 R C", "Cuero 2 R C", "Cuero 2 R C black",
    "Cuero 1 black R D", "Cuero 6 black R D",
    "Cuero jasp claro marron", "Cuero jasp caramelo", "Cuero jasp arena",
    "Vinil 8 lija", "Vinil 5 black", "Vinil 13 4", "Vinil 2",
    "Vinil 16 gris", "Vinil 17 tabaco", "Vinil 5 gris oscuro",
    "Vinil 5 Terracota", "Vinil 5 gris claro", "Vinil 5 cafe 2",
    "Vinil perfo ame black", "Vinil M 12", "Vinil M 21", "Vinil M 6",
    "Vinil M 7", "Vinil M 4", "Vinil M 18 R A", "Vinil M 3 parecido",
    "Bravia black", "Fury", "Piso rocky tp gris", "Piso rocky tp negro",
    "Docca dark gray", "Golden", "Bristol Forro Textil Gris", "Bristol Tapiceria Textil Negro",
    "Camaro", "Lazzio docca negro", "Techo soft gris claro", "Titanium varation azabache",
    "Berlin negro", "Iberia negro", "Titanium varation charol", "Bravia tabaco",
    "Bravia Blanco Puro", "Bravia capuchino", "Vertigo beige", "Vertigo stone",
    "Bravia Raton", "Vertigo blanco puro", "Vertigo naranja", "Vertigo turquesa",
    "Preston aluminizado", "Ecopiso point grey", "Bravia verde", "Piso tax azul",
    "Piso andes 099k", "Piso tax negro", "Suizo beige 003K", "Piso tax gris",
    "Bilbao negro", "Becerro Copa", "Celta negro 099k", "Sevila",
    "Becerro gris 10248K", "Suizo negro", "Becerro cafe 59285", "Becerro gris 10196",
    "Bravia azul", "Bravia Ice", "Vertigo marfil",
    "Diseno 1 gris", "Diseno perforado gris", "Eclipse gris", "Eclipse negro",
    "Titanium varation dark graphite", "Celta gris",
    "Vinil m 7", "Vinil M 7 p", "Vinil M 7 liso", "Vinil M corrugado", "Vinil m 21p",
    "Vinil 120 gris r n", "Vinil 124", "Vinil 5 plata", "Vinil lija", "Vinil moto",
    "Vinil M 16 gris", "Vinil 5 cafe",
    "Konan 099 10665 PLATA", "Konan 099 30471 AZUL", "Konan 099 205 ROJO", "Konan 099 10867 GRIS",
    "Vinil M 18 azul", "Vinil M 51 gris", "Vinil M 55", "Vinil M 79 cafe",
    "Vinil cafe jasp", "Vinil M 7 gris", "Vinil VI 58 gris", "Vinil M 1 OPTRA",
    "Vinil M liso gris", "Vinil M 2 OPTRA", "Vinil M 78", "Vinil M 7 camel",
    "Vinil M 51 camel", "Vinil 117 gris", "Vinil 133", "Vinil T 14 gris",
    "Vinil M 57 Gris",
    "Moto Diamante", "Moto M 22", "Cuero 2 R A", "Cuero 6 R D",
    "Diseno B 720 gris", "Diseno B 720 Black", "Piso Patriot Azul",
    "EAF 72", "EA 45", "EA 34", "EAF 10 2", "EAF 58 jasp",
    "EAF 8", "EAF 22 c r", "EAF 37 gris", "Alcantara", "EAF 12 vino",
    "EAF 172", "EAF 13 azul", "EAF 22 5 r",
    "Telas c esp", "Telas s esp", "Cuero jasp Morron cl", "Cuero jasp capuchino",
    "Piso liberty grey", "Piso patriot grey", "Tela americana s c", "Tela europea s c",
    "Tapizon velour rosa", "Tapizon velour cafe", "Tapizon velour nude",
    "EA 137 rosa", "EA 137 azul", "EA 137 gris", "EA 84 c r", "EA 63",
    "EA 161", "EA 162 gris", "EA 167", "EA 169 black", "EA 169 gris",
    "EA 164", "EA 165 gris", "EA 171 azul", "EA 173 gris", "EA 174 black",
    "EA 176 gris", "EAF 7 dark grey", "EA s c",
    "FC col 16 gris", "FC col s c", "FC col perfo", "FC col 6 black",
    "FCB mana black", "FCB gls black", "FCB treasure", "FCB transformer",
    "FCB tube", "FCB renoir", "FCB britar", "EA 89", "FC 218", "FCB negro",
    "Col 6 gris", "Tela chi", "Jeep mesh", "FC col 14 beige", "FC 499",
    "Malla color gris", "MC 002",
    "Techo 3", "Techo 4", "Techo 5", "Techo 7", "Techo 8", "Techo 9"
]
